server {
    listen 80;
    
    # Responde a cualquier petición (ideal para cuando uses tu IP de Azure o nip.io)
    server_name _; 

    # 1. Rutear a Certificados (Puerto interno 5000)
    location /certificados/ {
        proxy_pass http://certificados:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Cookie $http_cookie;
        proxy_pass_header Set-Cookie;
        proxy_redirect / /certificados/;

        sub_filter 'href="/static/' 'href="/certificados/static/';
        sub_filter 'href="/login' 'href="/certificados/login';
        sub_filter 'href="/logout' 'href="/certificados/logout';
        sub_filter 'href="/certificado/' 'href="/certificados/certificado/';
        sub_filter 'action="/login' 'action="/certificados/login';
        sub_filter 'action="/logout' 'action="/certificados/logout';
        sub_filter 'href="/"' 'href="/certificados/"';
        sub_filter_once off;
        sub_filter_types text/html;
    }

    # 2. Rutear a SUM (Puerto interno 5000)
    location /sum/ {
        proxy_pass http://sum-web:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_redirect / /sum/;

        sub_filter 'href="/static/' 'href="/sum/static/';
        sub_filter 'action="/buscar"' 'action="/sum/buscar"';
        sub_filter 'href="/logout"' 'href="/sum/logout"';
        sub_filter 'action="/admin/cmd"' 'action="/sum/admin/cmd"';
        sub_filter 'action="/admin/diag"' 'action="/sum/admin/diag"';
        sub_filter 'href="/"' 'href="/sum/"';
        sub_filter 'action="/"' 'action="/sum/"';
        sub_filter_once off;
        sub_filter_types text/html;
    }

    # 3. Rutear a Trámite Legacy (Puerto interno 80 de Apache)
    location /tramite/ {
        proxy_pass http://tramite-legacy:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_redirect / /tramite/;
        proxy_buffering on;

        sub_filter 'href="/backups/"' 'href="/tramite/backups/"';
        sub_filter_once off;
        sub_filter_types text/html;
    }
}
